### ISSUE TITLE
LoadError: None of the selected providers can install dependency [nettle|GnuTLS].

### ISSUE THREAD

**Issue by EricForgy** [one-more-minute/Mux.jl#14]
Hi,

I don't know if this is an issue with Mux, but when I try to add Mux, I get some errors. I copied below my latest attempt. I'm on a Windows Server on an Azure VM with Julia 0.4 rc1.

It looks like I can grab all required packages except Nettle and GnuTLS.

Any ideas? Thanks

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of BinDeps...
INFO: Updating cache of SHA...
INFO: Updating cache of Docile...
INFO: Computing changes...
INFO: Upgrading BinDeps: v0.3.15 => v0.3.16
INFO: Upgrading Docile: v0.5.18 => v0.5.19
INFO: Upgrading SHA: v0.1.1 => v0.1.2

julia> Pkg.checkout("Mux")
INFO: Checking out Mux master...
INFO: Pulling Mux latest master...
INFO: No packages to install, update or remove

julia> Pkg.build("Mux")
INFO: Building HttpParser
INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab8c228f50e8cf4d505283b1-pri
mary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab8c228f50e8cf
4d505283b1-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab8c228f50e8cf
4d505283b1-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab8c228f50e8cf
4d505283b1-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab8c228f50e8cf
4d505283b1-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab8c228f50e8cf
4d505283b1-primary.xml.gz
WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/7a833a399a331e96db98ada98a76ed38c7938db5ab
8c228f50e8cf4d505283b1-primary.xml.gz
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15e49ed2bd844600b506ef1c-pri
mary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15e49ed2bd8446
00b506ef1c-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15e49ed2bd8446
00b506ef1c-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15e49ed2bd8446
00b506ef1c-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15e49ed2bd8446
00b506ef1c-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15e49ed2bd8446
00b506ef1c-primary.xml.gz
WARNING: received error 0 while downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/d261b71262ba05d3f6598be3de875ce921b225cc15
e49ed2bd844600b506ef1c-primary.xml.gz
INFO: Building Nettle
===========================================================================================[ ERROR: Nettle ]============================================================================================

LoadError: None of the selected providers can install dependency nettle.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\Eric.Forgy\.julia\v0.4\Nettle\deps\build.jl, in expression starting on line 39

========================================================================================================================================================================================================

INFO: Building GnuTLS
===========================================================================================[ ERROR: GnuTLS ]============================================================================================

LoadError: None of the selected providers can install dependency gnutls.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\Eric.Forgy\.julia\v0.4\GnuTLS\deps\build.jl, in expression starting on line 59

========================================================================================================================================================================================================

============================================================================================[ BUILD ERRORS ]============================================================================================

WARNING: Nettle and GnuTLS had build errors.

 - packages with build errors remain installed in C:\Users\Eric.Forgy\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("Nettle", "GnuTLS")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================================================================================================

**Comment by one-more-minute** [comment]
Looks like the step that failed is the build step for Nettle – your best bet would be to ask over at the Nettle.jl repo.

**Comment by EricForgy** [comment]
Makes sense. Thanks!

**Comment by rohitvarkey** [comment]
https://github.com/JuliaLang/WinRPM.jl/issues/47 Could this be the problem?

**Comment by rohitvarkey** [comment]
https://github.com/staticfloat/Nettle.jl/issues/48 also seems relevant!
